FROM selenium/node-firefox-debug:3.141.59

USER root
RUN apt-get update && apt-get install -y pulseaudio

USER seluser
ADD docker-firefox-entrypoint.sh /opt/bin/

CMD ["/opt/bin/docker-firefox-entrypoint.sh"]
