version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.14159
    container_name: selenium-hub
    logging:
      driver: "none"
    ports:
      - "4444:4444"  # Only used if we run wdio locally and not via docker
    deploy:
      resources:
        limits:
          memory: 2G

  chrome:
    image: selenium/node-chrome-debug:3.14159
    container_name: chrome
    depends_on:
      - selenium-hub
    ports:
      - "5902:5900"  # VNC for debugging things
    logging:
      driver: "none"
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
    deploy:
      resources:
        limits:
          memory: 2G

  firefox:
    build:
      context: .
      dockerfile: Dockerfile-firefox-with-pulseaudio
    container_name: firefox
    depends_on:
      - selenium-hub
    ports:
      - "5901:5900"  # VNC for debugging things
    logging:
      driver: "none"
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
    deploy:
      resources:
        limits:
          memory: 2G

  licode:
    image: lynckia/licode:develop
    container_name: licode
    environment:
      MIN_PORT: 30000
      MAX_PORT: 35000
    logging:
      driver: "none"
    volumes:
    - ./licode_default.js:/opt/licode/scripts/licode_default.js
    deploy:
      resources:
        limits:
          memory: 2G

  integration:
    build:
      context: .
      dockerfile: Dockerfile-tests
    container_name: integration
    environment:
      HUB_HOST: selenium-hub
      LICODE_HOST: licode
    depends_on:
    - selenium-hub
    - chrome
    - firefox
    - licode
    volumes:
    - ./errorShots:/tmp/errorShots
    - ./reports:/tmp/reports
    deploy:
      resources:
        limits:
          memory: 2G
