hub:
  image: selenium/hub
  ports:
  - 4444:4444

chrome:
  image: selenium/node-chrome
  links:
  - hub:hub
  - integration:integration
  volumes:
  - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952

firefox:
  image: selenium/node-firefox
  environment:
    HUB_PORT_4444_TCP_ADDR: hub
  links:
  - hub:hub
  - integration:integration

licode:
  image: lynckia/licode:develop
  environment:
    MIN_PORT: 30000
    MAX_PORT: 30150

integration:
  build: .
  container_name: integration
  environment:
    HUB_PORT_4444_TCP_ADDR: hub
    LICODE_ADDR: licode
  links:
  - hub:hub
  - licode:licode
