version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:4.9

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin


      - run:
          name: Install Dependencies
          command: |
            npm install --only=dev

      - run:
          name: Selenium
          command: |
            docker-compose up -d

      - run:
          name: Pull latest docker image
          command: |
            docker pull lynckia/licode:develop

      - run:
          name: Run Licode
          command: |
            MIN_PORT=30000; MAX_PORT=30050; docker run --name licode -p  3000:3000 -p $MIN_PORT-$MAX_PORT:$MIN_PORT-$MAX_PORT/udp -p 3001:3001  -p 8080:8080 -e "MIN_PORT=$MIN_PORT" -e "MAX_PORT=$MAX_PORT" -e "PUBLIC_IP=127.0.0.1" lynckia/licode:develop
          background: true

      - run:
          name: Tests
          command: |
            npm test


      - run: echo ok!
