version: 2.0

jobs:
  build:
    machine: true

    steps:
      - checkout
      - run:
          name: Prepare folders
          command: |
            mkdir -p errorShots
            mkdir -p reports/junit
            chmod a+w errorShots reports reports/junit

      - run:
          name: Create docker instances
          command: |
            docker-compose build

      - run:
          name: Tests
          command: |
            docker-compose up --exit-code-from integration --scale firefox=2 --scale chrome=2 --scale licode=1 --scale integration=1

      - store_test_results:
          path: ./reports

      - store_artifacts:
          path: ./errorShots

workflows:
  version: 2
  test:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
