version: 2.0

jobs:
  build:
    machine:
      - image: circleci/node:4.9

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Create docker instances
          command: |
            docker-compose build

      - run:
          name: Start selenium
          command: |
            docker-compose up -d selenium-hub chrome firefox

      - run:
          name: Start licode
          command: |
            docker-compose up -d licode

      - run:
          name: Run Licode
          command: |
            MIN_PORT=30000; MAX_PORT=30050; docker run --name licode -p  3000:3000 -p $MIN_PORT-$MAX_PORT:$MIN_PORT-$MAX_PORT/udp -p 3001:3001  -p 8080:8080 -e "MIN_PORT=$MIN_PORT" -e "MAX_PORT=$MAX_PORT" -e "PUBLIC_IP=127.0.0.1" lynckia/licode:develop
          background: true

      - run:
          name: Tests
          command: |
            docker-compose up integration

      - store_test_results:
          path: /reports

      - store_artifacts:
          path: /errorShots
